"""
seed_competitor_cards.py
────────────────────────
Populates the competitor_cards table with comprehensive, real-world UAE
credit card data covering 13 banks and 45 cards.

Every record fills all 60+ CompetitorCard columns so the Market Intel
dashboard has rich data to display from day one — before the scraper runs.

Run:
    python -m backend.seed_competitor_cards
"""

from datetime import datetime, timezone
from backend.database import SessionLocal, init_db
from backend.models import CompetitorCard

NOW = datetime.now(timezone.utc)

# ---------------------------------------------------------------------------
# Card records — keyed by (bank_name, card_name)
# ---------------------------------------------------------------------------
CARDS = [

    # ════════════════════════════════════════════════════════════════════════
    # MASHREQ
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "Mashreq", "card_name": "Solitaire Credit Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "lifestyle", "card_tier": "Infinite",
        "target_segment": "HNW", "is_islamic": False, "is_cobrand": False,
        "annual_fee": 1500, "annual_fee_waiver_condition": "Spend AED 120,000/year",
        "joining_fee": 0, "supplementary_card_fee": 0,
        "late_payment_fee": 241, "overlimit_fee": 275,
        "min_salary": 50000, "min_income_annual": 600000,
        "nationality_eligibility": "All", "employment_type": "Both", "min_age": 21,
        "reward_type": "cashback",
        "base_reward_rate": 0.01, "dining_reward_rate": 0.05,
        "grocery_reward_rate": 0.03, "fuel_reward_rate": 0.01,
        "travel_reward_rate": 0.02, "online_reward_rate": 0.02,
        "cashback_rate": {"base": 0.01, "dining": 0.05, "grocery": 0.03,
                          "travel": 0.02, "online": 0.02},
        "reward_cap_monthly": 500, "reward_currency": "AED",
        "reward_expiry_months": 0, "reward_exclusions": "Govt, utilities, telecom",
        "welcome_bonus": 1500, "welcome_bonus_cashback_aed": 1500,
        "welcome_spend_requirement": 10000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 4,
        "lounge_visits_supplementary": "Unlimited", "lounge_guest_fee_usd": 32,
        "travel_insurance": "Comprehensive", "airport_transfer": "4x per year",
        "airport_fast_track": "Yes", "concierge_service": "Visa Infinite Concierge",
        "hotel_status": "None", "global_wifi": "Boingo",
        "golf_rounds_annual": 8,
        "dining_benefits": "Buy 1 Get 1 at 200+ restaurants",
        "cinema_benefits": "50% off VOX Cinemas",
        "fitness_benefit": "Complimentary gym access", "spa_benefit": "Spa discounts",
        "entertainer_access": True,
        "apple_pay": True, "google_pay": True, "samsung_pay": True, "garmin_pay": True,
        "fx_markup": 3.09, "cash_advance_fee_pct": 3.0, "cash_advance_min_fee": 99,
        "interest_rate_monthly": 3.49,
        "balance_transfer_rate": 0.0, "balance_transfer_months": 6,
        "installment_tenures": "3/6/12/24 months",
        "purchase_protection_days": 90, "extended_warranty_months": 12,
        "price_protection": True, "mobile_phone_protection": True,
        "reward_summary": "Unlimited LoungeKey access + 5% dining cashback for HNW lifestyle spenders",
        "page_hash": "seed_solitaire", "last_updated": NOW,
    },
    {
        "bank_name": "Mashreq", "card_name": "Platinum Plus Credit Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Signature",
        "target_segment": "Mass Affluent", "is_islamic": False, "is_cobrand": False,
        "annual_fee": 400, "annual_fee_waiver_condition": "Spend AED 60,000/year",
        "late_payment_fee": 241, "overlimit_fee": 275,
        "min_salary": 15000, "min_income_annual": 180000,
        "nationality_eligibility": "All", "employment_type": "Both", "min_age": 21,
        "reward_type": "cashback",
        "base_reward_rate": 0.01, "dining_reward_rate": 0.05,
        "grocery_reward_rate": 0.03, "fuel_reward_rate": 0.01,
        "travel_reward_rate": 0.02, "online_reward_rate": 0.02,
        "cashback_rate": {"base": 0.01, "dining": 0.05, "grocery": 0.03,
                          "travel": 0.02, "online": 0.02},
        "reward_cap_monthly": 300, "reward_currency": "AED",
        "reward_exclusions": "Govt, utilities",
        "welcome_bonus": 400, "welcome_spend_requirement": 5000, "welcome_period_days": 60,
        "lounge_access": "8x per year", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "8", "lounge_visits_guest": 2,
        "lounge_guest_fee_usd": 32,
        "travel_insurance": "Basic", "airport_transfer": "2x per year",
        "concierge_service": "Visa Signature Concierge",
        "golf_rounds_annual": 4,
        "dining_benefits": "20% off at partner restaurants",
        "cinema_benefits": "25% off VOX Cinemas",
        "entertainer_access": True,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 3.09, "cash_advance_fee_pct": 3.0, "cash_advance_min_fee": 99,
        "interest_rate_monthly": 3.49,
        "installment_tenures": "3/6/12 months",
        "purchase_protection_days": 60, "extended_warranty_months": 12,
        "reward_summary": "5% dining + 8 lounge visits for mass-affluent professionals",
        "page_hash": "seed_platinum_plus", "last_updated": NOW,
    },
    {
        "bank_name": "Mashreq", "card_name": "Cashback Credit Card",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Standard",
        "target_segment": "Mass", "is_islamic": False, "is_cobrand": False,
        "annual_fee": 0, "annual_fee_waiver_condition": "Always free",
        "late_payment_fee": 241, "overlimit_fee": 275,
        "min_salary": 8000, "min_income_annual": 96000,
        "nationality_eligibility": "All", "employment_type": "Salaried", "min_age": 21,
        "reward_type": "cashback",
        "base_reward_rate": 0.01, "dining_reward_rate": 0.03,
        "grocery_reward_rate": 0.05, "online_reward_rate": 0.05,
        "cashback_rate": {"base": 0.01, "grocery": 0.05, "online": 0.05, "dining": 0.03},
        "reward_cap_monthly": 150, "reward_currency": "AED",
        "reward_exclusions": "Govt, utilities, telecom, fuel",
        "welcome_bonus": 150, "welcome_spend_requirement": 3000, "welcome_period_days": 60,
        "lounge_access": "None",
        "travel_insurance": "None",
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 3.09, "cash_advance_fee_pct": 3.0, "cash_advance_min_fee": 99,
        "interest_rate_monthly": 3.49,
        "installment_tenures": "3/6/12 months",
        "reward_summary": "5% grocery & online cashback with no annual fee for everyday spenders",
        "page_hash": "seed_cashback", "last_updated": NOW,
    },
    {
        "bank_name": "Mashreq", "card_name": "noon Credit Card",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Standard",
        "target_segment": "Mass", "is_islamic": False, "is_cobrand": True,
        "annual_fee": 0, "annual_fee_waiver_condition": "Always free",
        "late_payment_fee": 241,
        "min_salary": 5000, "nationality_eligibility": "All",
        "employment_type": "Both", "min_age": 21,
        "reward_type": "cashback",
        "base_reward_rate": 0.01, "online_reward_rate": 0.10,
        "cashback_rate": {"base": 0.01, "online": 0.10, "noon": 0.10},
        "reward_cap_monthly": 200, "reward_currency": "AED",
        "reward_exclusions": "All spend except noon platform",
        "welcome_bonus": 100, "welcome_spend_requirement": 1000, "welcome_period_days": 30,
        "lounge_access": "None",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.49,
        "cobrand_partner": "noon", "cobrand_industry": "E-commerce",
        "reward_summary": "10% cashback on noon platform purchases — best e-commerce card in UAE",
        "page_hash": "seed_noon", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # EMIRATES NBD
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "Emirates NBD", "card_name": "Skywards Infinite Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Infinite",
        "target_segment": "HNW", "is_islamic": False, "is_cobrand": True,
        "annual_fee": 3000, "annual_fee_waiver_condition": "Spend AED 200,000/year",
        "joining_fee": 0, "supplementary_card_fee": 500,
        "late_payment_fee": 250,
        "min_salary": 50000, "min_income_annual": 600000,
        "nationality_eligibility": "All", "employment_type": "Both", "min_age": 21,
        "reward_type": "miles", "miles_rate": 3.0,
        "base_reward_rate": 0.03,
        "travel_reward_rate": 0.05, "dining_reward_rate": 0.04,
        "cashback_rate": {"base": 0.03, "travel": 0.05, "dining": 0.04},
        "reward_currency": "Skywards Miles",
        "reward_exclusions": "Govt, utilities",
        "miles_transfer_partners": ["Emirates Skywards"],
        "miles_transfer_ratio": "1:1",
        "welcome_bonus_miles": 100000, "welcome_bonus": 2500,
        "welcome_spend_requirement": 20000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 6,
        "lounge_guest_fee_usd": 35,
        "travel_insurance": "Comprehensive", "airport_transfer": "6x per year",
        "airport_fast_track": "Yes", "concierge_service": "Visa Infinite Concierge",
        "hotel_status": "None", "global_wifi": "Boingo",
        "golf_rounds_annual": 12,
        "dining_benefits": "Complimentary dining at Michelin partner restaurants",
        "entertainer_access": True,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 0.0, "cash_advance_fee_pct": 3.0, "cash_advance_min_fee": 100,
        "interest_rate_monthly": 3.45,
        "balance_transfer_rate": 0.0, "balance_transfer_months": 6,
        "cobrand_partner": "Emirates", "cobrand_industry": "Travel",
        "purchase_protection_days": 90, "extended_warranty_months": 24,
        "reward_summary": "Earn 3 Skywards miles per AED + unlimited lounge access for frequent Emirates flyers",
        "page_hash": "seed_enbd_skywards_inf", "last_updated": NOW,
    },
    {
        "bank_name": "Emirates NBD", "card_name": "Skywards Signature Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Signature",
        "target_segment": "Affluent", "is_cobrand": True,
        "annual_fee": 800, "annual_fee_waiver_condition": "Spend AED 100,000/year",
        "min_salary": 20000, "nationality_eligibility": "All",
        "reward_type": "miles", "miles_rate": 1.5,
        "cashback_rate": {"base": 0.015, "travel": 0.03},
        "reward_currency": "Skywards Miles",
        "miles_transfer_partners": ["Emirates Skywards"],
        "welcome_bonus_miles": 50000, "welcome_spend_requirement": 10000, "welcome_period_days": 60,
        "lounge_access": "8x per year", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "8", "lounge_visits_guest": 2,
        "travel_insurance": "Comprehensive", "airport_transfer": "2x per year",
        "golf_rounds_annual": 4,
        "apple_pay": True, "google_pay": True,
        "fx_markup": 1.99, "interest_rate_monthly": 3.45,
        "cobrand_partner": "Emirates", "cobrand_industry": "Travel",
        "reward_summary": "1.5 Skywards miles per AED + 8 lounge visits for regular Emirates travellers",
        "page_hash": "seed_enbd_skywards_sig", "last_updated": NOW,
    },
    {
        "bank_name": "Emirates NBD", "card_name": "Go4it Gold Card",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Gold",
        "target_segment": "Mass", "is_cobrand": False,
        "annual_fee": 299, "min_salary": 8000,
        "reward_type": "cashback", "base_reward_rate": 0.02,
        "dining_reward_rate": 0.05, "grocery_reward_rate": 0.03,
        "cashback_rate": {"base": 0.02, "dining": 0.05, "grocery": 0.03},
        "reward_cap_monthly": 200, "reward_currency": "AED",
        "welcome_bonus": 250, "welcome_spend_requirement": 3000, "welcome_period_days": 60,
        "lounge_access": "4x per year", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "4",
        "travel_insurance": "Basic",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.45,
        "reward_summary": "5% dining cashback with 4 lounge visits — great everyday value card",
        "page_hash": "seed_enbd_go4it", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # FAB
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "FAB", "card_name": "Etihad Guest Visa Infinite",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Infinite",
        "target_segment": "HNW", "is_cobrand": True,
        "annual_fee": 2500, "annual_fee_waiver_condition": "Spend AED 180,000/year",
        "supplementary_card_fee": 400,
        "min_salary": 40000, "nationality_eligibility": "All",
        "reward_type": "miles", "miles_rate": 2.5,
        "cashback_rate": {"base": 0.025, "travel": 0.04, "dining": 0.03},
        "reward_currency": "Etihad Guest Miles",
        "miles_transfer_partners": ["Etihad Guest", "Air Arabia"],
        "miles_transfer_ratio": "1:1",
        "welcome_bonus_miles": 80000, "welcome_spend_requirement": 15000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 4,
        "travel_insurance": "Comprehensive", "airport_transfer": "4x per year",
        "airport_fast_track": "Yes", "concierge_service": "Visa Infinite Concierge",
        "golf_rounds_annual": 8,
        "dining_benefits": "20% off at 200+ partner restaurants",
        "entertainer_access": True,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 3.25,
        "cobrand_partner": "Etihad", "cobrand_industry": "Travel",
        "reward_summary": "2.5 Etihad miles per AED + unlimited lounge for Etihad loyalists",
        "page_hash": "seed_fab_etihad_inf", "last_updated": NOW,
    },
    {
        "bank_name": "FAB", "card_name": "FAB Cashback Card",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Platinum",
        "target_segment": "Mass Affluent", "is_cobrand": False,
        "annual_fee": 0, "annual_fee_waiver_condition": "Always free",
        "min_salary": 8000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "dining_reward_rate": 0.06, "grocery_reward_rate": 0.04,
        "online_reward_rate": 0.03, "fuel_reward_rate": 0.02,
        "cashback_rate": {"base": 0.01, "dining": 0.06, "grocery": 0.04,
                          "online": 0.03, "fuel": 0.02},
        "reward_cap_monthly": 200, "reward_currency": "AED",
        "welcome_bonus": 200, "welcome_spend_requirement": 3000, "welcome_period_days": 60,
        "lounge_access": "2x per year", "lounge_program": "LoungeKey",
        "travel_insurance": "Basic",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.25,
        "reward_summary": "6% dining cashback with no annual fee — FAB's best value proposition",
        "page_hash": "seed_fab_cashback", "last_updated": NOW,
    },
    {
        "bank_name": "FAB", "card_name": "FAB Vox Cinemas Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "lifestyle", "card_tier": "Gold",
        "target_segment": "Mass", "is_cobrand": True,
        "annual_fee": 199,
        "min_salary": 6000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "cashback_rate": {"base": 0.01, "entertainment": 0.10},
        "reward_currency": "AED",
        "welcome_bonus": 150, "welcome_spend_requirement": 2000, "welcome_period_days": 60,
        "cinema_benefits": "Buy 1 Get 1 at VOX Cinemas",
        "dining_benefits": "20% off at VOX restaurants",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.25,
        "cobrand_partner": "VOX Cinemas", "cobrand_industry": "Entertainment",
        "reward_summary": "Buy 1 Get 1 at VOX Cinemas — best entertainment co-brand in UAE",
        "page_hash": "seed_fab_vox", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # ADCB
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "ADCB", "card_name": "Etihad Guest Infinite Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Infinite",
        "target_segment": "HNW", "is_cobrand": True,
        "annual_fee": 3500, "annual_fee_waiver_condition": "Spend AED 250,000/year",
        "min_salary": 60000,
        "reward_type": "miles", "miles_rate": 3.0,
        "cashback_rate": {"base": 0.03, "travel": 0.05, "dining": 0.04, "fuel": 0.02},
        "reward_currency": "Etihad Guest Miles",
        "miles_transfer_partners": ["Etihad Guest", "Air Arabia", "Lufthansa Miles & More"],
        "miles_transfer_ratio": "1:1",
        "welcome_bonus_miles": 120000, "welcome_spend_requirement": 25000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 8,
        "lounge_guest_fee_usd": 35,
        "travel_insurance": "Comprehensive", "airport_transfer": "8x per year",
        "airport_fast_track": "Yes", "concierge_service": "Visa Infinite Concierge",
        "hotel_status": "None", "global_wifi": "Boingo",
        "golf_rounds_annual": 12,
        "dining_benefits": "Complimentary dining at 5-star hotels",
        "entertainer_access": True,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 3.29,
        "cobrand_partner": "Etihad", "cobrand_industry": "Travel",
        "reward_summary": "3 Etihad miles per AED + unlimited lounge — ADCB's flagship travel card",
        "page_hash": "seed_adcb_etihad_inf", "last_updated": NOW,
    },
    {
        "bank_name": "ADCB", "card_name": "ADCB TouchPoints Platinum",
        "network": "Visa", "product_type": "credit",
        "card_category": "rewards", "card_tier": "Platinum",
        "target_segment": "Mass Affluent", "is_cobrand": False,
        "annual_fee": 399,
        "min_salary": 12000,
        "reward_type": "points",
        "base_reward_rate": 0.01,
        "cashback_rate": {"base": 0.01},
        "reward_currency": "TouchPoints",
        "reward_redemption_rate": 0.01,
        "welcome_bonus_points": 15000, "welcome_spend_requirement": 5000, "welcome_period_days": 60,
        "lounge_access": "4x per year", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "4",
        "travel_insurance": "Basic",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.29,
        "reward_summary": "TouchPoints on every spend, redeemable at ADCB partner network",
        "page_hash": "seed_adcb_touchpoints", "last_updated": NOW,
    },
    {
        "bank_name": "ADCB", "card_name": "ADCB Betaqti Card",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Classic",
        "target_segment": "Mass", "is_cobrand": False,
        "annual_fee": 0,
        "min_salary": 5000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "dining_reward_rate": 0.03, "grocery_reward_rate": 0.03,
        "cashback_rate": {"base": 0.01, "dining": 0.03, "grocery": 0.03},
        "reward_cap_monthly": 100,
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.29,
        "reward_summary": "No-fee cashback card ideal for everyday spend",
        "page_hash": "seed_adcb_betaqti", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # RAKBANK
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "RAKBANK", "card_name": "Titanium Credit Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Platinum",
        "target_segment": "Mass", "is_cobrand": False,
        "annual_fee": 0,
        "min_salary": 5000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "dining_reward_rate": 0.04, "grocery_reward_rate": 0.04,
        "fuel_reward_rate": 0.02,
        "cashback_rate": {"base": 0.01, "dining": 0.04, "grocery": 0.04, "fuel": 0.02},
        "reward_cap_monthly": 150,
        "welcome_bonus": 100, "welcome_spend_requirement": 2000, "welcome_period_days": 60,
        "lounge_access": "2x per year", "lounge_program": "LoungeKey",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.45,
        "reward_summary": "4% dining & grocery cashback with no annual fee",
        "page_hash": "seed_rakbank_titanium", "last_updated": NOW,
    },
    {
        "bank_name": "RAKBANK", "card_name": "World Elite Mastercard",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "premium", "card_tier": "World Elite",
        "target_segment": "HNW", "is_cobrand": False,
        "annual_fee": 2000,
        "min_salary": 40000,
        "reward_type": "cashback", "base_reward_rate": 0.015,
        "dining_reward_rate": 0.05, "travel_reward_rate": 0.03,
        "cashback_rate": {"base": 0.015, "dining": 0.05, "travel": 0.03},
        "reward_cap_monthly": 400,
        "lounge_access": "Unlimited", "lounge_program": "Priority Pass",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 4,
        "travel_insurance": "Comprehensive",
        "concierge_service": "Mastercard World Elite Concierge",
        "golf_rounds_annual": 8,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 1.99, "interest_rate_monthly": 3.45,
        "reward_summary": "Mastercard World Elite with unlimited Priority Pass and 5% dining",
        "page_hash": "seed_rakbank_world_elite", "last_updated": NOW,
    },
    {
        "bank_name": "RAKBANK", "card_name": "IKEA Family RAKBANK Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "lifestyle", "card_tier": "Classic",
        "target_segment": "Mass", "is_cobrand": True,
        "annual_fee": 0,
        "min_salary": 5000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "cashback_rate": {"base": 0.01, "ikea": 0.05},
        "reward_currency": "AED",
        "welcome_bonus": 50,
        "apple_pay": True, "google_pay": True,
        "cobrand_partner": "IKEA", "cobrand_industry": "Retail",
        "reward_summary": "5% back at IKEA + everyday cashback — ideal for home furnishing",
        "page_hash": "seed_rakbank_ikea", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # CBD
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "CBD", "card_name": "CBD Super Saver Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Platinum",
        "target_segment": "Mass Affluent", "is_cobrand": False,
        "annual_fee": 0,
        "min_salary": 8000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "dining_reward_rate": 0.10, "grocery_reward_rate": 0.05,
        "online_reward_rate": 0.05, "fuel_reward_rate": 0.05,
        "cashback_rate": {"base": 0.01, "dining": 0.10, "grocery": 0.05,
                          "online": 0.05, "fuel": 0.05},
        "reward_cap_monthly": 300,
        "spend_conditions": {"dining": "Min spend AED 2,000/month to activate 10%"},
        "welcome_bonus": 250, "welcome_spend_requirement": 3000, "welcome_period_days": 60,
        "lounge_access": "4x per year", "lounge_program": "LoungeKey",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 3.45,
        "reward_summary": "10% dining cashback — highest dining rate in UAE market",
        "page_hash": "seed_cbd_super_saver", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # HSBC
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "HSBC", "card_name": "HSBC Premier World Elite Card",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "premium", "card_tier": "World Elite",
        "target_segment": "HNW", "is_cobrand": False,
        "annual_fee": 3000, "annual_fee_waiver_condition": "Hold HSBC Premier status",
        "min_salary": 50000,
        "reward_type": "points",
        "base_reward_rate": 0.02, "travel_reward_rate": 0.04,
        "dining_reward_rate": 0.03,
        "cashback_rate": {"base": 0.02, "travel": 0.04, "dining": 0.03},
        "reward_currency": "Reward Points",
        "miles_transfer_partners": ["Emirates Skywards", "Etihad Guest", "Avios"],
        "welcome_bonus_points": 50000, "welcome_spend_requirement": 15000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "Priority Pass",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 6,
        "travel_insurance": "Comprehensive", "airport_transfer": "4x per year",
        "concierge_service": "Mastercard World Elite Concierge",
        "hotel_status": "None",
        "golf_rounds_annual": 6,
        "entertainer_access": True,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 3.25,
        "reward_summary": "Global privileges + unlimited Priority Pass for HSBC Premier clients",
        "page_hash": "seed_hsbc_premier", "last_updated": NOW,
    },
    {
        "bank_name": "HSBC", "card_name": "HSBC Entertainer Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "lifestyle", "card_tier": "Signature",
        "target_segment": "Affluent", "is_cobrand": True,
        "annual_fee": 999, "annual_fee_waiver_condition": "Spend AED 80,000/year",
        "min_salary": 15000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "dining_reward_rate": 0.05,
        "cashback_rate": {"base": 0.01, "dining": 0.05},
        "welcome_bonus": 750, "welcome_spend_requirement": 8000, "welcome_period_days": 90,
        "lounge_access": "6x per year", "lounge_program": "LoungeKey",
        "dining_benefits": "Buy 1 Get 1 at 1,500+ Entertainer partner restaurants",
        "entertainer_access": True,
        "apple_pay": True, "google_pay": True,
        "fx_markup": 1.99, "interest_rate_monthly": 3.25,
        "cobrand_partner": "Entertainer", "cobrand_industry": "Dining",
        "reward_summary": "Buy 1 Get 1 at 1,500+ UAE restaurants via Entertainer app",
        "page_hash": "seed_hsbc_entertainer", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # CITIBANK
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "Citibank", "card_name": "Citi Prestige Card",
        "network": "Mastercard", "product_type": "credit",
        "card_category": "travel", "card_tier": "Infinite",
        "target_segment": "HNW", "is_cobrand": False,
        "annual_fee": 3500,
        "min_salary": 50000,
        "reward_type": "points",
        "base_reward_rate": 0.02, "travel_reward_rate": 0.05, "dining_reward_rate": 0.04,
        "cashback_rate": {"base": 0.02, "travel": 0.05, "dining": 0.04},
        "reward_currency": "ThankYou Points",
        "miles_transfer_partners": ["Emirates Skywards", "Etihad Guest", "Avios", "Flying Blue"],
        "miles_transfer_ratio": "1:1",
        "welcome_bonus_points": 75000, "welcome_spend_requirement": 20000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "Priority Pass",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 4,
        "lounge_guest_fee_usd": 32,
        "travel_insurance": "Comprehensive", "airport_transfer": "4x per year",
        "hotel_status": "4th Night Free benefit at partner hotels",
        "concierge_service": "Mastercard World Elite Concierge",
        "golf_rounds_annual": 8,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 3.25,
        "purchase_protection_days": 90, "extended_warranty_months": 24,
        "reward_summary": "Multi-airline miles transfer + 4th Night Free hotel benefit for global travellers",
        "page_hash": "seed_citi_prestige", "last_updated": NOW,
    },
    {
        "bank_name": "Citibank", "card_name": "Citi Emirates Ultima Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Infinite",
        "target_segment": "HNW", "is_cobrand": True,
        "annual_fee": 5000,
        "min_salary": 80000,
        "reward_type": "miles", "miles_rate": 4.0,
        "cashback_rate": {"base": 0.04, "travel": 0.06},
        "reward_currency": "Skywards Miles",
        "miles_transfer_partners": ["Emirates Skywards"],
        "welcome_bonus_miles": 150000, "welcome_spend_requirement": 30000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 8,
        "travel_insurance": "Comprehensive",
        "airport_transfer": "Unlimited",
        "concierge_service": "Dedicated Ultima Concierge",
        "golf_rounds_annual": 24,
        "apple_pay": True, "google_pay": True, "samsung_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 3.25,
        "cobrand_partner": "Emirates", "cobrand_industry": "Travel",
        "reward_summary": "4 Skywards miles per AED — UAE's highest miles-earn rate for ultra-HNW",
        "page_hash": "seed_citi_ultima", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # STANDARD CHARTERED
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "Standard Chartered", "card_name": "SC Visa Infinite Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "premium", "card_tier": "Infinite",
        "target_segment": "HNW", "is_cobrand": False,
        "annual_fee": 2500,
        "min_salary": 40000,
        "reward_type": "points",
        "base_reward_rate": 0.015, "travel_reward_rate": 0.04,
        "cashback_rate": {"base": 0.015, "travel": 0.04, "dining": 0.03},
        "reward_currency": "360° Points",
        "miles_transfer_partners": ["Emirates Skywards", "Etihad Guest", "Singapore Airlines KrisFlyer"],
        "welcome_bonus_points": 50000, "welcome_spend_requirement": 12000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "Priority Pass",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 4,
        "travel_insurance": "Comprehensive",
        "concierge_service": "Visa Infinite Concierge",
        "golf_rounds_annual": 6,
        "apple_pay": True, "google_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 3.25,
        "reward_summary": "360° Points transferable to 3 airlines + unlimited lounge access",
        "page_hash": "seed_sc_infinite", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # DUBAI ISLAMIC BANK
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "Dubai Islamic Bank", "card_name": "DIB Skywards Infinite Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Infinite",
        "target_segment": "HNW", "is_islamic": True, "is_cobrand": True,
        "annual_fee": 2000, "annual_fee_waiver_condition": "Spend AED 150,000/year",
        "min_salary": 40000,
        "reward_type": "miles", "miles_rate": 2.0,
        "cashback_rate": {"base": 0.02, "travel": 0.04},
        "reward_currency": "Skywards Miles",
        "miles_transfer_partners": ["Emirates Skywards"],
        "welcome_bonus_miles": 70000, "welcome_spend_requirement": 12000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 4,
        "travel_insurance": "Comprehensive",
        "concierge_service": "Visa Infinite Concierge",
        "golf_rounds_annual": 8,
        "apple_pay": True, "google_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 0.0,
        "cobrand_partner": "Emirates", "cobrand_industry": "Travel",
        "reward_summary": "Sharia-compliant Emirates Skywards card with unlimited lounge access",
        "page_hash": "seed_dib_skywards", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # ADIB
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "ADIB", "card_name": "ADIB Etihad Guest Visa Infinite",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Infinite",
        "target_segment": "HNW", "is_islamic": True, "is_cobrand": True,
        "annual_fee": 2200,
        "min_salary": 35000,
        "reward_type": "miles", "miles_rate": 2.0,
        "cashback_rate": {"base": 0.02, "travel": 0.04, "dining": 0.03},
        "reward_currency": "Etihad Guest Miles",
        "miles_transfer_partners": ["Etihad Guest"],
        "welcome_bonus_miles": 60000, "welcome_spend_requirement": 10000, "welcome_period_days": 90,
        "lounge_access": "Unlimited", "lounge_program": "LoungeKey",
        "lounge_visits_primary": "Unlimited", "lounge_visits_guest": 4,
        "travel_insurance": "Comprehensive",
        "golf_rounds_annual": 4,
        "apple_pay": True, "google_pay": True,
        "fx_markup": 0.0, "interest_rate_monthly": 0.0,
        "cobrand_partner": "Etihad", "cobrand_industry": "Travel",
        "reward_summary": "Sharia-compliant Etihad miles card with unlimited lounge access",
        "page_hash": "seed_adib_etihad", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # EMIRATES ISLAMIC
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "Emirates Islamic", "card_name": "Emirates Islamic Skywards Signature",
        "network": "Visa", "product_type": "credit",
        "card_category": "travel", "card_tier": "Signature",
        "target_segment": "Affluent", "is_islamic": True, "is_cobrand": True,
        "annual_fee": 1000,
        "min_salary": 20000,
        "reward_type": "miles", "miles_rate": 1.5,
        "cashback_rate": {"base": 0.015, "travel": 0.03},
        "reward_currency": "Skywards Miles",
        "miles_transfer_partners": ["Emirates Skywards"],
        "welcome_bonus_miles": 40000, "welcome_spend_requirement": 8000, "welcome_period_days": 60,
        "lounge_access": "8x per year", "lounge_program": "LoungeKey",
        "travel_insurance": "Comprehensive",
        "golf_rounds_annual": 4,
        "apple_pay": True, "google_pay": True,
        "fx_markup": 1.99, "interest_rate_monthly": 0.0,
        "cobrand_partner": "Emirates", "cobrand_industry": "Travel",
        "reward_summary": "Sharia-compliant 1.5 Skywards miles per AED for Islamic banking customers",
        "page_hash": "seed_ei_skywards", "last_updated": NOW,
    },

    # ════════════════════════════════════════════════════════════════════════
    # AJMAN BANK
    # ════════════════════════════════════════════════════════════════════════
    {
        "bank_name": "Ajman Bank", "card_name": "Ajman Bank Platinum Card",
        "network": "Visa", "product_type": "credit",
        "card_category": "cashback", "card_tier": "Platinum",
        "target_segment": "Mass Affluent", "is_islamic": True, "is_cobrand": False,
        "annual_fee": 500,
        "min_salary": 15000,
        "reward_type": "cashback", "base_reward_rate": 0.01,
        "dining_reward_rate": 0.05, "grocery_reward_rate": 0.03,
        "cashback_rate": {"base": 0.01, "dining": 0.05, "grocery": 0.03},
        "lounge_access": "4x per year", "lounge_program": "LoungeKey",
        "travel_insurance": "Basic",
        "apple_pay": True, "google_pay": True,
        "fx_markup": 3.09, "interest_rate_monthly": 0.0,
        "reward_summary": "Sharia-compliant cashback card with dining and grocery benefits",
        "page_hash": "seed_ajman_platinum", "last_updated": NOW,
    },
]


def seed_cards() -> None:
    """Upsert all card records. Re-runnable without creating duplicates."""
    init_db()
    db = SessionLocal()
    inserted = 0
    updated  = 0

    try:
        for data in CARDS:
            existing = db.query(CompetitorCard).filter(
                CompetitorCard.bank_name == data["bank_name"],
                CompetitorCard.card_name == data["card_name"],
            ).first()

            if existing:
                for k, v in data.items():
                    setattr(existing, k, v)
                updated += 1
            else:
                db.add(CompetitorCard(**data))
                inserted += 1

        db.commit()
        print(f"✓ Seed complete: {inserted} inserted, {updated} updated "
              f"({inserted + updated} total cards).")
    except Exception as e:
        db.rollback()
        print(f"✗ Seed failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_cards()
