"""
Seed comprehensive UAE credit card market data.
Run once: python -m backend.seed_cards
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.database import SessionLocal, init_db
from backend.models import CompetitorCard

UAE_CARDS = [
    # ─── MASHREQ ──────────────────────────────────────────────────────────────
    {
        "bank_name": "Mashreq",
        "card_name": "Solitaire",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 1500,
        "min_salary": 25000,
        "cashback_rate": {"base": 0.02, "lifestyle": 0.05},
        "miles_rate": 2.0,
        "welcome_bonus": 5000,
        "fx_markup": 0,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "Mashreq Solitaire — premium Visa card. Unlimited lounge access, concierge 24/7, FX-free, travel insurance, 5% back on lifestyle & dining, 2% everywhere.",
    },
    {
        "bank_name": "Mashreq",
        "card_name": "Platinum Plus",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 400,
        "min_salary": 10000,
        "cashback_rate": {"base": 0.01, "dining": 0.03, "travel": 0.03},
        "miles_rate": 1.5,
        "welcome_bonus": 1000,
        "fx_markup": 1.99,
        "lounge_access": "6x per year",
        "travel_insurance": "Included",
        "reward_summary": "Mashreq Platinum Plus — 3% back on dining & travel, 1% on all other spend, 6 free lounge visits, travel insurance, AED 1,000 welcome bonus.",
    },
    {
        "bank_name": "Mashreq",
        "card_name": "Cashback",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "online": 0.05, "grocery": 0.02},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Mashreq Cashback — no annual fee. 5% cashback online, 2% grocery & supermarkets, 1% on all other spend.",
    },
    {
        "bank_name": "Mashreq",
        "card_name": "noon",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "lifestyle",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "noon": 0.05, "grocery": 0.02},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Mashreq noon Visa — co-branded with noon.com. 5% back on noon.com, 2% grocery, 1% elsewhere. No annual fee.",
    },

    # ─── EMIRATES NBD ─────────────────────────────────────────────────────────
    {
        "bank_name": "Emirates NBD",
        "card_name": "Titanium Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "grocery": 0.035, "dining": 0.035},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.75,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "3.5% cashback on grocery & dining, 1% on all other spends. No annual fee.",
    },
    {
        "bank_name": "Emirates NBD",
        "card_name": "Skywards Signature",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "travel",
        "annual_fee": 200,
        "min_salary": 8000,
        "cashback_rate": {"base": 0},
        "miles_rate": 1.5,
        "welcome_bonus": 2000,
        "fx_markup": 1.99,
        "lounge_access": "4x per year",
        "travel_insurance": "Included",
        "reward_summary": "1.5 Skywards miles/AED domestic, 3 miles/AED international. 2K bonus miles on approval.",
    },
    {
        "bank_name": "Emirates NBD",
        "card_name": "Skywards Infinite",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "travel",
        "annual_fee": 900,
        "min_salary": 20000,
        "cashback_rate": {"base": 0},
        "miles_rate": 3.0,
        "welcome_bonus": 10000,
        "fx_markup": 0.99,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "3 Skywards miles/AED international, unlimited lounge, 10K welcome miles, travel insurance.",
    },
    {
        "bank_name": "Emirates NBD",
        "card_name": "Lulu Titanium Credit Card",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "lifestyle",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "lulu": 0.10, "grocery": 0.03},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "10% cashback at Lulu Hypermarket, 3% grocery, 1% everywhere else. Free annual fee.",
    },
    {
        "bank_name": "Emirates NBD",
        "card_name": "Beyond Visa Infinite",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 2000,
        "min_salary": 35000,
        "cashback_rate": {"base": 0.01},
        "miles_rate": 2.0,
        "welcome_bonus": 8000,
        "fx_markup": 0,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "Unlimited lounge, 2 Skywards miles/AED, FX-free, concierge, 8K welcome miles.",
    },

    # ─── FAB (First Abu Dhabi Bank) ───────────────────────────────────────────
    {
        "bank_name": "FAB",
        "card_name": "Cashback Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 8000,
        "cashback_rate": {"base": 0.01, "online": 0.05, "contactless": 0.02},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "5% cashback online, 2% contactless, 1% everywhere. No annual fee.",
    },
    {
        "bank_name": "FAB",
        "card_name": "Etihad Guest Platinum",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "travel",
        "annual_fee": 200,
        "min_salary": 8000,
        "cashback_rate": {"base": 0},
        "miles_rate": 1.5,
        "welcome_bonus": 5000,
        "fx_markup": 1.99,
        "lounge_access": "4x per year",
        "travel_insurance": "Included",
        "reward_summary": "1.5 Etihad Guest miles/AED, 4 lounge visits, 5K bonus miles, travel insurance.",
    },
    {
        "bank_name": "FAB",
        "card_name": "World Elite Mastercard",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 1500,
        "min_salary": 25000,
        "cashback_rate": {"base": 0},
        "miles_rate": 3.0,
        "welcome_bonus": 15000,
        "fx_markup": 0,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "3 Etihad miles/AED, unlimited Priority Pass, FX-free, 15K welcome miles, concierge.",
    },
    {
        "bank_name": "FAB",
        "card_name": "Islamic Finance Cashback Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "islamic",
        "annual_fee": 0,
        "min_salary": 8000,
        "cashback_rate": {"base": 0.01, "online": 0.05},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Sharia-compliant. 5% cashback online, 1% elsewhere. Profit-rate based, no interest.",
    },

    # ─── ADCB ─────────────────────────────────────────────────────────────────
    {
        "bank_name": "ADCB",
        "card_name": "Simplylife Cashback Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.03},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Flat 3% cashback on all spends. No annual fee. Simple and straightforward.",
    },
    {
        "bank_name": "ADCB",
        "card_name": "Lulu ADCB Titanium Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "lifestyle",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "lulu": 0.10},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "10% cashback at Lulu Hypermarket, earn ADCB Touchpoints on all spends.",
    },
    {
        "bank_name": "ADCB",
        "card_name": "Touchpoints Platinum Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "rewards",
        "annual_fee": 500,
        "min_salary": 10000,
        "cashback_rate": {"base": 0.01},
        "miles_rate": 1.5,
        "welcome_bonus": 0,
        "fx_markup": 1.99,
        "lounge_access": "4x per year",
        "travel_insurance": "Included",
        "reward_summary": "ADCB Touchpoints on all spends, 4 lounge visits, travel insurance, dining privileges.",
    },
    {
        "bank_name": "ADCB",
        "card_name": "Touchpoints Infinite Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 1200,
        "min_salary": 20000,
        "cashback_rate": {"base": 0.01},
        "miles_rate": 2.5,
        "welcome_bonus": 5000,
        "fx_markup": 0.99,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "Unlimited Priority Pass, 2.5 Touchpoints/AED, 5K welcome bonus, concierge, travel cover.",
    },

    # ─── RAKBANK ──────────────────────────────────────────────────────────────
    {
        "bank_name": "RAKBANK",
        "card_name": "RAKretail Mastercard",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 3000,
        "cashback_rate": {"base": 0.01},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "1% cashback on all spends. No annual fee. Low salary requirement AED 3,000.",
    },
    {
        "bank_name": "RAKBANK",
        "card_name": "RAKBANK Titanium Mastercard",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "dining": 0.02, "shopping": 0.02},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.75,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "2% cashback on dining & shopping, 1% on everything else. No annual fee.",
    },
    {
        "bank_name": "RAKBANK",
        "card_name": "World Elite Mastercard",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 500,
        "min_salary": 15000,
        "cashback_rate": {"base": 0.03},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 1.50,
        "lounge_access": "8x per year",
        "travel_insurance": "Included",
        "reward_summary": "3% cashback on all spends, 8 lounge visits/year, travel insurance, dining discounts.",
    },
    {
        "bank_name": "RAKBANK",
        "card_name": "Infinite Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 1000,
        "min_salary": 20000,
        "cashback_rate": {"base": 0.03},
        "miles_rate": None,
        "welcome_bonus": 3000,
        "fx_markup": 1.00,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "3% cashback, unlimited lounge, AED 3K welcome cashback, travel & medical insurance.",
    },

    # ─── HSBC ─────────────────────────────────────────────────────────────────
    {
        "bank_name": "HSBC",
        "card_name": "Cashback Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.015},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Flat 1.5% unlimited cashback on all spends. No annual fee. No cashback cap.",
    },
    {
        "bank_name": "HSBC",
        "card_name": "Premier Mastercard",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "lifestyle",
        "annual_fee": 0,
        "min_salary": 25000,
        "cashback_rate": {"base": 0.01},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 1.50,
        "lounge_access": "4x per year",
        "travel_insurance": "Included",
        "reward_summary": "For HSBC Premier customers. 1% cashback, 4 lounge visits, travel privileges.",
    },
    {
        "bank_name": "HSBC",
        "card_name": "Premier World Elite Mastercard",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 1200,
        "min_salary": 40000,
        "cashback_rate": {"base": 0.015},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 0,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "1.5% cashback globally, unlimited Priority Pass, FX-free international, concierge 24/7.",
    },

    # ─── STANDARD CHARTERED ───────────────────────────────────────────────────
    {
        "bank_name": "Standard Chartered",
        "card_name": "Simply Cash Credit Card",
        "network": "Mastercard",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.02},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Flat 2% unlimited cashback on all spends. Simple product with no caps.",
    },
    {
        "bank_name": "Standard Chartered",
        "card_name": "Ultimate Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 0,
        "min_salary": 30000,
        "cashback_rate": {"base": 0.015},
        "miles_rate": 2.0,
        "welcome_bonus": 0,
        "fx_markup": 0,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "For SC Priority Banking clients. FX-free, unlimited lounge, 360° reward points.",
    },

    # ─── ADIB ─────────────────────────────────────────────────────────────────
    {
        "bank_name": "ADIB",
        "card_name": "Cashback Visa",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "islamic",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "dining": 0.05, "telecom": 0.05, "supermarket": 0.03},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.75,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Sharia-compliant. 5% on dining & telecom, 3% supermarkets, 1% everywhere. No fee.",
    },
    {
        "bank_name": "ADIB",
        "card_name": "Etihad Guest Platinum",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "travel",
        "annual_fee": 200,
        "min_salary": 10000,
        "cashback_rate": {"base": 0},
        "miles_rate": 1.5,
        "welcome_bonus": 5000,
        "fx_markup": 1.99,
        "lounge_access": "4x per year",
        "travel_insurance": "Included",
        "reward_summary": "Islamic travel card. 1.5 Etihad miles/AED, 4 lounge visits, Sharia-compliant.",
    },
    {
        "bank_name": "ADIB",
        "card_name": "Etihad Guest Infinite",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 900,
        "min_salary": 20000,
        "cashback_rate": {"base": 0},
        "miles_rate": 3.0,
        "welcome_bonus": 12000,
        "fx_markup": 0.99,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "Islamic premium. 3 Etihad miles/AED, unlimited lounge, 12K miles welcome, concierge.",
    },

    # ─── EMIRATES ISLAMIC ─────────────────────────────────────────────────────
    {
        "bank_name": "Emirates Islamic",
        "card_name": "Cashback Plus Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "islamic",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01, "dining": 0.05, "entertainment": 0.03},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Sharia-compliant. 5% dining, 3% entertainment, 1% all other. No annual fee.",
    },
    {
        "bank_name": "Emirates Islamic",
        "card_name": "AeriaOne Visa Infinite",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 1500,
        "min_salary": 25000,
        "cashback_rate": {"base": 0},
        "miles_rate": 2.5,
        "welcome_bonus": 10000,
        "fx_markup": 0.99,
        "lounge_access": "Unlimited",
        "travel_insurance": "Included",
        "reward_summary": "Islamic premium. 2.5 Skywards miles/AED, unlimited lounge, 10K bonus miles, Sharia.",
    },

    # ─── CBD ─────────────────────────────────────────────────────────────────
    {
        "bank_name": "CBD",
        "card_name": "Super Saver Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "cashback",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.10},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "10% cashback (capped at AED 400/month). No annual fee. Best-in-class cashback rate.",
    },
    {
        "bank_name": "CBD",
        "card_name": "CBD Visa Infinite",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 500,
        "min_salary": 15000,
        "cashback_rate": {"base": 0.01},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 1.99,
        "lounge_access": "8x per year",
        "travel_insurance": "Included",
        "reward_summary": "Visa Infinite benefits, 8 lounge visits, travel insurance, dining offers in UAE.",
    },

    # ─── DIB (Dubai Islamic Bank) ─────────────────────────────────────────────
    {
        "bank_name": "Dubai Islamic Bank",
        "card_name": "Titanium Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "islamic",
        "annual_fee": 0,
        "min_salary": 5000,
        "cashback_rate": {"base": 0.01},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 2.99,
        "lounge_access": "None",
        "travel_insurance": "Not included",
        "reward_summary": "Sharia-compliant titanium card. 1% cashback, no annual fee, halal rewards.",
    },
    {
        "bank_name": "Dubai Islamic Bank",
        "card_name": "Infinite Credit Card",
        "network": "Visa",
        "product_type": "credit",
        "card_category": "premium",
        "annual_fee": 600,
        "min_salary": 15000,
        "cashback_rate": {"base": 0.015},
        "miles_rate": None,
        "welcome_bonus": 0,
        "fx_markup": 1.99,
        "lounge_access": "6x per year",
        "travel_insurance": "Included",
        "reward_summary": "Islamic premium. 1.5% cashback, 6 lounge visits, Sharia-compliant, travel cover.",
    },
]


def seed():
    init_db()
    db = SessionLocal()
    try:
        existing = db.query(CompetitorCard).count()
        if existing > 0:
            print(f"DB already has {existing} cards — clearing and re-seeding.")
            db.query(CompetitorCard).delete()
            db.commit()

        for card_data in UAE_CARDS:
            card = CompetitorCard(**card_data)
            db.add(card)

        db.commit()
        print(f"Seeded {len(UAE_CARDS)} UAE credit cards across "
              f"{len(set(c['bank_name'] for c in UAE_CARDS))} banks.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
